export interface StatGlossaryEntry {
  readonly term: string
  readonly name: string
  readonly description: string
  readonly formula?: string
}

const ENTRIES: readonly StatGlossaryEntry[] = [
  { term: '1B', name: 'Singles', description: 'Hits that put the batter safely on first base.' },
  { term: '1st-P Str', name: 'First-pitch strike rate', formula: 'Plate appearances starting 0–1 ÷ batters faced × 100', description: 'How often a pitcher begins a matchup with a strike.' },
  { term: '2B', name: 'Doubles', description: 'Hits that put the batter safely on second base.' },
  { term: '3B', name: 'Triples', description: 'Hits that put the batter safely on third base.' },
  { term: 'AB', name: 'At bats', description: 'Official batting chances, excluding walks, sacrifices, and hit-by-pitches.' },
  { term: 'AVG', name: 'Batting average', formula: 'H ÷ AB', description: 'How often a batter records a hit in an official at-bat.' },
  { term: 'Avg / Min / Max', name: 'Average, minimum, and maximum', description: 'Summary values for the selected set of pitches or batted balls.' },
  { term: 'Avg EV / Max EV', name: 'Exit-velocity summary', description: 'Average or fastest tracked exit velocity in the selected sample.' },
  { term: 'Avg LA', name: 'Average launch angle', description: 'Mean vertical angle of tracked batted balls, in degrees.' },
  { term: 'BABIP', name: 'Batting average on balls in play', formula: '(H − HR) ÷ (AB − K − HR + SF)', description: 'How often a non-home-run ball in play becomes a hit.' },
  { term: 'Balls', name: 'Balls', description: 'Pitches called outside the strike zone without a swing.' },
  { term: 'Bat / Bat Speed', name: 'Bat speed', description: 'Speed of the bat at impact, measured in miles per hour.' },
  { term: 'BB', name: 'Walks', description: 'Plate appearances ending with the batter awarded first base on four balls.' },
  { term: 'BB%', name: 'Walk rate', formula: 'BB ÷ PA × 100', description: 'Share of plate appearances ending in a walk.' },
  { term: 'BF / Batters', name: 'Batters faced', description: 'Total hitters who completed a plate appearance against the pitcher.' },
  { term: 'Brk Ang', name: 'Break angle', description: 'Direction of a pitch’s movement as it approaches the plate.' },
  { term: 'Brk Horz', name: 'Horizontal break', description: 'Side-to-side movement of a pitch, measured in inches.' },
  { term: 'Brk Len', name: 'Break length', description: 'Total measured distance of a pitch’s break.' },
  { term: 'Brk Vert', name: 'Vertical break', description: 'Up-or-down movement relative to a spinless trajectory.' },
  { term: 'Called', name: 'Called strikes', description: 'Taken pitches ruled strikes by the umpire.' },
  { term: 'Chase %', name: 'Chase rate', formula: 'Swings outside zone ÷ pitches outside zone × 100', description: 'How often a hitter swings at pitches outside the strike zone.' },
  { term: 'Count', name: 'Ball-strike count', description: 'Current balls and strikes in the plate appearance.' },
  { term: 'CSW %', name: 'Called strikes plus whiffs', formula: '(Called strikes + swinging strikes) ÷ pitches × 100', description: 'Share of pitches that produce a called strike or a miss.' },
  { term: 'Dist / Distance', name: 'Hit distance', description: 'Estimated distance traveled by a batted ball, in feet.' },
  { term: 'E', name: 'Errors', description: 'Defensive mistakes charged by the official scorer.' },
  { term: 'End Velo', name: 'Plate velocity', description: 'Pitch speed near home plate after air resistance slows it.' },
  { term: 'ERA', name: 'Earned run average', formula: 'ER ÷ IP × 9', description: 'Earned runs allowed per nine innings; lower is better.' },
  { term: 'ERA+', name: 'Adjusted ERA', formula: '100 × league ERA ÷ park-adjusted ERA', description: 'ERA adjusted for league and park; 100 is average and higher is better.' },
  { term: 'ER', name: 'Earned runs', description: 'Runs charged to a pitcher excluding those enabled by errors or passed balls.' },
  { term: 'EV / Exit Velo', name: 'Exit velocity', description: 'Speed of the ball immediately after contact, in miles per hour.' },
  { term: 'Extension', name: 'Pitcher extension', description: 'How far toward home plate the pitcher releases the ball.' },
  { term: 'FIP', name: 'Fielding independent pitching', formula: '(13×HR + 3×(BB+HBP) − 2×K) ÷ IP + 3.15', description: 'ERA-scale estimate using outcomes largely controlled by the pitcher.' },
  { term: 'Foul', name: 'Foul balls', description: 'Batted pitches landing outside fair territory.' },
  { term: 'G / Games', name: 'Games', description: 'Games in which the player appeared.' },
  { term: 'GB%', name: 'Ground-ball rate', formula: 'Ground balls ÷ batted balls × 100', description: 'Share of batted balls hit on the ground.' },
  { term: 'GS / Starts', name: 'Games started', description: 'Games in which the pitcher was the starting pitcher.' },
  { term: 'H / Hits', name: 'Hits', description: 'Times a batter safely reaches base on a fair ball without an error.' },
  { term: 'Hardness', name: 'Contact hardness', description: 'Feed classification of how firmly a ball was hit.' },
  { term: 'Hard hit', name: 'Hard-hit rate', formula: 'Batted balls at least 95 mph ÷ tracked batted balls × 100', description: 'Share of tracked contact hit at Statcast’s hard-hit threshold.' },
  { term: 'HBP', name: 'Hit by pitch', description: 'Times a batter is awarded first after being struck by a pitch.' },
  { term: 'HR', name: 'Home runs', description: 'Fair balls that allow the batter to score without being put out.' },
  { term: 'HR/9', name: 'Home runs per nine', formula: 'HR ÷ IP × 9', description: 'Home runs allowed per nine innings pitched.' },
  { term: 'In Play', name: 'Balls in play', description: 'Pitches contacted into fair territory.' },
  { term: 'Inn / Inning', name: 'Inning', description: 'Current or recorded inning of play.' },
  { term: 'IP', name: 'Innings pitched', description: 'Pitching workload, where .1 and .2 represent one and two outs.' },
  { term: 'ISO', name: 'Isolated power', formula: 'SLG − AVG', description: 'Extra bases per at-bat, isolating power from singles.' },
  { term: 'K / SO', name: 'Strikeouts', description: 'Plate appearances ending with three strikes.' },
  { term: 'K%', name: 'Strikeout rate', formula: 'K ÷ PA × 100', description: 'Share of plate appearances ending in a strikeout.' },
  { term: 'LA / Launch °', name: 'Launch angle', description: 'Vertical angle of a batted ball at contact, in degrees.' },
  { term: 'OBP', name: 'On-base percentage', formula: '(H + BB + HBP) ÷ (AB + BB + HBP + SF)', description: 'How often a batter reaches base without a fielding error.' },
  { term: 'OPS', name: 'On-base plus slugging', formula: 'OBP + SLG', description: 'Combined measure of reaching base and hitting for power.' },
  { term: 'Opp AVG', name: 'Opponent batting average', formula: 'Opponent H ÷ opponent AB', description: 'Batting average allowed by a pitcher.' },
  { term: 'Outs', name: 'Outs', description: 'Outs recorded in the current half-inning.' },
  { term: 'P / Pitches', name: 'Pitches', description: 'Total pitches thrown or seen in the selected scope.' },
  { term: 'P/BF', name: 'Pitches per batter faced', formula: 'Pitches ÷ BF', description: 'Average pitches required to complete each batter faced.' },
  { term: 'PA', name: 'Plate appearances', description: 'Completed batting turns, including walks, sacrifices, and hit-by-pitches.' },
  { term: 'PA/BF', name: 'Plate appearances or batters faced', description: 'Batting opportunities for a hitter or completed matchups for a pitcher.' },
  { term: 'Plate Time', name: 'Plate time', description: 'Elapsed time from pitch release until the ball reaches home plate.' },
  { term: 'R', name: 'Runs', description: 'Players who safely reached home plate to score.' },
  { term: 'RBI', name: 'Runs batted in', description: 'Runs credited to a batter because of the plate appearance.' },
  { term: 'Runners', name: 'Baserunners', description: 'Occupied bases in the current game state.' },
  { term: 'Seen', name: 'Pitch usage seen', formula: 'Pitch type count ÷ all pitches seen × 100', description: 'Share of pitches a batter saw from each pitch type.' },
  { term: 'SLG', name: 'Slugging percentage', formula: 'Total bases ÷ AB', description: 'Total bases per at-bat, weighting extra-base hits.' },
  { term: 'Spin', name: 'Spin rate', description: 'Pitch rotation measured in revolutions per minute.' },
  { term: 'Str / Strikes', name: 'Strikes', description: 'Pitches called strikes, swung at and missed, fouled, or put in play.' },
  { term: 'Str% / Strike %', name: 'Strike rate', formula: 'Strikes ÷ pitches × 100', description: 'Share of all pitches recorded as strikes.' },
  { term: 'SV', name: 'Saves', description: 'Games finished while preserving a qualifying lead.' },
  { term: 'Swing %', name: 'Swing rate', formula: 'Swings ÷ pitches × 100', description: 'Share of pitches at which the batter swings.' },
  { term: 'Swing Tilt', name: 'Swing tilt', description: 'Vertical orientation of the bat path through the hitting zone.' },
  { term: 'SwStr / Whiff', name: 'Swinging strikes', formula: 'Misses ÷ swings × 100 for Whiff %', description: 'Swings that miss the pitch; Whiff % expresses their share of swings.' },
  { term: 'Taken %', name: 'Taken-strike rate', formula: 'Called strikes ÷ taken pitches × 100', description: 'Share of pitches not swung at that were called strikes.' },
  { term: 'Thru Ord', name: 'Times through order', description: 'How many times the pitcher has worked through the batting order.' },
  { term: 'TB', name: 'Total bases', formula: '1B + 2×2B + 3×3B + 4×HR', description: 'Bases credited from hits, weighting extra-base hits.' },
  { term: 'Trend / Recent / Last N', name: 'Velocity trend', description: 'Recent average pitch velocity and its change from the earlier sample.' },
  { term: 'Type / Pitch', name: 'Pitch type', description: 'Classified pitch, such as four-seam fastball, slider, or changeup.' },
  { term: 'Usage', name: 'Pitch usage', formula: 'Pitch type count ÷ all pitches × 100', description: 'Share of a pitcher’s tracked pitches belonging to one pitch type.' },
  { term: 'Velo', name: 'Pitch velocity', description: 'Pitch speed near release, in miles per hour.' },
  { term: 'Watchability', name: 'Watchability score', formula: 'Pregame and live ratings blended to a 0–100 score', description: 'Ranks how compelling a game is using matchup quality, stakes, leverage, closeness, and live drama.' },
  { term: 'WHIP', name: 'Walks and hits per inning pitched', formula: '(BB + H) ÷ IP', description: 'Baserunners allowed per inning via walks and hits; lower is better.' },
  { term: 'wOBA', name: 'Weighted on-base average', formula: 'Season-weighted offensive events ÷ PA', description: 'Values each way of reaching base by its typical run impact.' },
  { term: 'wRC+', name: 'Weighted runs created plus', formula: 'Park- and league-adjusted runs per PA, indexed to 100', description: 'Total offensive production; 100 is league average and higher is better.' },
  { term: 'xwOBAcon', name: 'Expected wOBA on contact', description: 'Expected quality of contact based on exit velocity and launch angle.' },
  { term: 'Zone %', name: 'Zone rate', formula: 'Pitches in zone ÷ pitches with zone data × 100', description: 'Share of pitches that cross the strike zone.' },
]

export const STAT_GLOSSARY: readonly StatGlossaryEntry[] = [...ENTRIES].sort((left, right) =>
  left.term.localeCompare(right.term, undefined, { sensitivity: 'base' }),
)
